baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Turismo en parque de Ordesa y Monte Perdido'
theme = 'hugo-Clarity'
link_externo="https://www.ordesa.net/"


[menu]

  [[menu.main]]
    identifier = "Lugares de interes"
    name = "Lugares interesantes"
    url = "/Lugares de Interes"
    weight = 3
  [[menu.main]]
    identifier = "Excursiones"
    name = "Excursiones"
    url = "/excursiones"
    weight = 2
  [[menu.main]]
    identifier = "Alojamiento"
    name = "Alojamiento"
    url = "/alojamiento"
    weight=1


    [taxonomies]
category = "categories"
tag = "tags"
series = "series"



[params]
link_externo= "https://www.ordesa.net/"
css=["css/estilos.css"]


